name: Production Release Artifacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Multiple OS Binaries and Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go/src/github.com/syniol/rock-paper-scissor-lizard-spock
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.24.0
      - uses: actions/checkout@v3
        with:
          path: 'go/src/github.com/syniol/rock-paper-scissor-lizard-spock'

      - name: Build Binaries
        run: make

      - name: Upload and Create a Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag_name: ${{ github.ref_name }}
          files: go/src/github.com/syniol/rock-paper-scissor-lizard-spock/dist/*
          fail_on_unmatched_files: true
