name: Production Release Artifacts

on:
  push:
    branches: [ "main" ]

#on:
#  release:
#    types:
#      - published

jobs:
  build:
    name: Build Multiple OS Binaries
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go/src/github.com/syniol/rock-paper-scissor-lizard-spock
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.24.0
      - uses: actions/checkout@v3
        with:
          path: 'go/src/github.com/syniol/rock-paper-scissor-lizard-spock'

      - name: Build Binaries
        run: go build -o ./dist/cli ./cmd/cli.go

      - name: Upload Artifact
        uses: actions/download-artifact@v4

  upload:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4

      - name: List the downloaded files
        run: pwd && ls -la

#      - name: Upload to release
#        uses: softprops/action-gh-release@v2
#        with:
#          token: ${{secrets.GITHUB_TOKEN}}
#          tag_name: ${{github.event.release.name}}
#          files: ./*/*
#          fail_on_unmatched_files: true
